config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/gallery'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @character = Character.all
  end
end

#Lavariable de instancia recibe todos los personajes que pertenecen a la clase del modelo

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>HowartsRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link
    href="https://fonts.googleapis.com/css2?family=Metal+Mania&family=Open+Sans:wght@400;700&family=Pacifico&family=Playfair:wght@300&display=swap"
    rel="stylesheet">
  <link rel="icon" type="image/png" href="<%= asset_path('1.png') %>">
</head>

<body>

  <nav class="navbar navbar-expand-lg fondonavbar">
    <div class="container-fluid textos">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav container-fluid">
          <!--<ul class="navbar-nav ms-auto me-5">-->
          <li class="nav-item">
            <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button"
              data-mdb-ripple-color="dark"><i class="fas fa-broom"></i></a>
          </li>
          <li class="nav-item">
            <%= link_to "Home", pages_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Galeria", pages_gallery_path, class:"nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="imagenfondo">
    <%= yield %>
  </div>

  <footer class="footer">
    <div class=" container-fluid text-center p-3">
      2023 Warner Bros:
      <section class="text-dark">
        Todos los derechos reservados
      </section>
      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-twitter"></i></a>
      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-facebook-f"></i></a>
      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-google"></i></a>
      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-instagram"></i></a>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"> </script>

</body>

</html>

app/views/pages/gallery.html.erb
<div class="container1">
  <h1> ¡PELICULAS DE TU SAGA FAVORITA! </h1>
</div>


<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag '11.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
    <div class="carousel-item dos2">
      <%= image_tag '12.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '13.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '14.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '150.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '16.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '17.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '18.jpg', class: "d-block mx-auto img-fluid" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/index.html.erb
<div class="container1">
    <h1>BIENVENIDO A HOWARTS</h1>
    <h2> PASA EL MOUSE POR SOBRE LA IMAGEN</h2>
</div>

<div class="container">
    <div class="row">
        <div class="col-7">
            <h3 class=titulo> PERSONAJES DE LA PELICULA </h3>

            <table class="table table-striped">
            <thead>
                <tr>
                    <th> Nombre </th>
                    <th> Locación </th>
                    <th> Casa </th>
                </tr>
                </thead>
                <tbody>
                <% @character.each do |x| %>
                <tr>
                    <td> <%= x.name %></td>
                    <td> <%= x.location %> </td>
                    <td> <%= x.house %></td>
                </tr>
                <% end %>
                </tbody>
            </table>
        </div>

        <div class="col-5">
            <div class="d-flex align-items-center  justify-content-center">
                <%= image_tag '9.png', class: "img-fluid", alt:"imagendecasas", style: "width: 1000px; height:700px; object-fit:cover; margin-bottom:40px; " %>
            </div>
        </div>
    </div>
</div>